# render.yaml

services:
  - type: web
    name: telegram-bot
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: BOT_SECRET_PASSWORD
        sync: false
      - key: FILE_RFP_EXCEL_COUNT
        value: "200"
